#!/usr/bin/env python
"""Derive source-image face boxes aligned to face-crop-plus crop indices.

Outputs lines:
  CROP_ALIGN_BOX_COUNT=<n>
  CROP_ALIGN_BOX_<i>=<x>,<y>,<w>,<h>

The index i is intended to map to crop filename suffix _i generated by
face-crop-plus in strategy=all mode.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description="Probe source boxes for face-crop-plus indices")
    parser.add_argument("--image", required=True, help="Input image path")
    parser.add_argument("--det-threshold", type=float, default=0.90, help="RetinaFace confidence threshold")
    parser.add_argument("--resize-size", type=int, default=3072, help="Interim detector/cropper resize size")
    parser.add_argument("--output-size", type=int, default=2048, help="Cropper output face size")
    parser.add_argument("--face-factor", type=float, default=0.65, help="Cropper face factor")
    parser.add_argument("--max-faces", type=int, default=0, help="Optional cap (0 means no cap)")
    return parser.parse_args()


def _clip_box(x, y, w, h, img_w, img_h):
    x = int(round(x))
    y = int(round(y))
    w = int(round(w))
    h = int(round(h))
    x = max(0, min(x, max(0, img_w - 1)))
    y = max(0, min(y, max(0, img_h - 1)))
    w = max(8, min(w, max(8, img_w - x)))
    h = max(8, min(h, max(8, img_h - y)))
    return (x, y, w, h)


def _box_from_landmarks(landmarks_src, landmarks_tgt, out_w, out_h, allow_skew, img_w, img_h):
    import cv2
    import numpy as np

    transform_fn = cv2.estimateAffine2D if allow_skew else cv2.estimateAffinePartial2D
    mat = transform_fn(
        landmarks_src.astype("float32"),
        landmarks_tgt.astype("float32"),
        ransacReprojThreshold=np.inf,
    )[0]
    if mat is None:
        return None

    mat_inv = cv2.invertAffineTransform(mat)
    corners = np.array(
        [[[0.0, 0.0], [float(out_w - 1), 0.0], [float(out_w - 1), float(out_h - 1)], [0.0, float(out_h - 1)]]],
        dtype="float32",
    )
    src_quad = cv2.transform(corners, mat_inv)[0]

    min_x = max(0.0, min(float(img_w - 1), float(src_quad[:, 0].min())))
    min_y = max(0.0, min(float(img_h - 1), float(src_quad[:, 1].min())))
    max_x = max(0.0, min(float(img_w), float(src_quad[:, 0].max())))
    max_y = max(0.0, min(float(img_h), float(src_quad[:, 1].max())))

    return _clip_box(min_x, min_y, max_x - min_x, max_y - min_y, img_w, img_h)


def main():
    args = parse_args()
    image_path = Path(args.image)
    if (not image_path.exists()) or (not image_path.is_file()):
        print(f"ERROR: image not found: {image_path}", file=sys.stderr)
        return 2

    try:
        import cv2
        import torch
        from face_crop_plus.cropper import Cropper
        from face_crop_plus.utils import as_batch, as_tensor, read_images
    except Exception as exc:
        print(f"ERROR: import failed: {exc}", file=sys.stderr)
        return 3

    img_bgr = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
    if img_bgr is None:
        print(f"ERROR: could not read image: {image_path}", file=sys.stderr)
        return 4
    img_h, img_w = img_bgr.shape[:2]

    device = "cuda" if torch.cuda.is_available() else "cpu"
    try:
        cropper = Cropper(
            output_size=[int(args.output_size), int(args.output_size)],
            output_format="png",
            resize_size=[int(args.resize_size), int(args.resize_size)],
            face_factor=float(args.face_factor),
            strategy="all",
            padding="constant",
            allow_skew=False,
            landmarks=None,
            attr_groups=None,
            mask_groups=None,
            det_threshold=float(args.det_threshold),
            enh_threshold=None,
            batch_size=1,
            num_processes=1,
            device=device,
        )
    except Exception as exc:
        print(f"ERROR: cropper init failed: {exc}", file=sys.stderr)
        return 5

    try:
        images, file_names = read_images([image_path.name], str(image_path.parent))
        if len(images) == 0:
            print("CROP_ALIGN_BOX_COUNT=0")
            return 0

        batch, unscales, paddings = as_batch(images, cropper.resize_size, padding_mode="constant")
        batch_t = as_tensor(batch, cropper.device)
        landmarks, indices = cropper.det_model.predict(batch_t)
        if len(landmarks) == 0:
            print("CROP_ALIGN_BOX_COUNT=0")
            return 0

        # Undo padding exactly as face-crop-plus does in process_batch.
        landmarks = landmarks - paddings[indices][:, None, [2, 0]]

        if len(unscales) == 0:
            unscale = 1.0
        else:
            unscale = float(unscales[0])
            if unscale <= 0:
                unscale = 1.0

        out_w, out_h = cropper.output_size
        resized_w = max(1, int(round(float(img_w) * float(unscale))))
        resized_h = max(1, int(round(float(img_h) * float(unscale))))
        boxes = []
        for lms in landmarks:
            box_resized = _box_from_landmarks(
                lms,
                cropper.landmarks_target,
                out_w=out_w,
                out_h=out_h,
                allow_skew=bool(cropper.allow_skew),
                img_w=resized_w,
                img_h=resized_h,
            )
            if box_resized is None:
                continue

            rx, ry, rw, rh = box_resized
            ox = rx / unscale
            oy = ry / unscale
            ow = rw / unscale
            oh = rh / unscale
            box_orig = _clip_box(ox, oy, ow, oh, img_w, img_h)
            boxes.append(box_orig)
    except Exception as exc:
        print(f"ERROR: probe failed: {exc}", file=sys.stderr)
        return 6

    if args.max_faces and args.max_faces > 0:
        boxes = boxes[: int(args.max_faces)]

    print(f"CROP_ALIGN_BOX_COUNT={len(boxes)}")
    for i, (x, y, w, h) in enumerate(boxes):
        print(f"CROP_ALIGN_BOX_{i}={x},{y},{w},{h}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
